Add check key length
reimagined/resolve-cloud-common pull request #113
Opened 2020-12-21 16:15 UTC by Lykoi18

2020-12-21 16:33 UTC, MrCheater approved these changes

2020-12-21 16:40 UTC, timbset requested changes

2020-12-21 16:40 UTC, timbset commented on acm/importCertificate.ts
> +    if (keySize > 4096) {
The condition will be false for keySize equal to 4096. You likely mean greater or equal.

2020-12-21 20:53 UTC, IhostVlad approved these changes

2020-12-22 08:50 UTC, timbset approved these changes

2020-12-22 08:51 UTC, merged